---
- name: Install rhscon-server
  hosts: skyring-server
  gather_facts: no
  vars:
    cdn_user_name: <user@redhat.com>
    cdn_user_pwd: <password>
    cdn_pool_id: 8a85f9823e3d5e43013e3ddd4e9509c4
  remote_user: root
  tasks:
  - name: Registering to CDN
    shell: subscription-manager register --username='{{ cdn_user_name }}' --password='{{ cdn_user_pwd }}'
  - name: Attaching the Pool
    shell: subscription-manager attach --pool='{{ cdn_pool_id }}'
  - name: Disable all the repos
    shell: subscription-manager repos --disable='*'
  - name: Enabling Repos
    shell: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-rhceph-1.3-calamari-rpms  --enable=rhel-7-server-rhceph-1.3-mon-rpms --enable=rh-gluster-3-for-rhel-7-server-rpms --enable=rhel-7-server-optional-rpms
  - name: Yum Update
    shell: yum update -y
  - name: Installing Yum Utils
    shell: yum install yum-utils wget -y
  - name: Adding Jenkins Repo
    shell: wget http://jenkins.lab.eng.blr.redhat.com/rhscon/rhscon.repo -P /etc/yum.repos.d/
  - name: Adding RHSCON-2 Puddle Repo
    shell: yum-config-manager --add http://dev-puddle.ceph.redhat.com/puddles/rhscon/2/2016-03-30.3/RHSCON-2/x86_64/os/
  - name: Installing rhscon packages
    shell: yum install rhscon-core rhscon-ceph rhscon-ui -y --nogpgcheck 
  - name: Stop Firewalld Service
    shell: systemctl stop firewalld.service
  - name: Disable Firewalld Service
    shell: systemctl disable firewalld.service
  - name: Flush Firewall Rules
    shell: iptables --flush


